-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Quiz
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Quiz` DEFAULT CHARACTER SET utf8 ;
USE `Quiz` ;

CREATE TABLE IF NOT EXISTS `Quiz`.`players` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `results` INT(11) NULL DEFAULT 0,
  `time` time (6) NULL DEFAULT 0,
  
  PRIMARY KEY (`id`))  
  ENGINE = InnoDB
  AUTO_INCREMENT = 3
  DEFAULT CHARACTER SET = utf8
  COLLATE = utf8_unicode_ci; 
  
  CREATE TABLE IF NOT EXISTS `Quiz`.`questions` (
  `questionid` INT(11) NOT NULL AUTO_INCREMENT,
  `categoryid` INT(11) NOT NULL DEFAULT 0,
  `question` VARCHAR(99) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  
  PRIMARY KEY (`questionid`))  
  ENGINE = InnoDB
  AUTO_INCREMENT = 3
  DEFAULT CHARACTER SET = utf8
  COLLATE = utf8_unicode_ci; 
  
  CREATE TABLE IF NOT EXISTS `Quiz`.`answers` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `questionid` INT (11) NOT NULL DEFAULT 0,
  `answer` VARCHAR(99) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `correct_answer` TINYINT(1) NULL DEFAULT false,
  
  PRIMARY KEY (`id`))  
  ENGINE = InnoDB
  AUTO_INCREMENT = 3
  DEFAULT CHARACTER SET = utf8
  COLLATE = utf8_unicode_ci;
  
  CREATE TABLE IF NOT EXISTS `Quiz`.`category` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(99) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  
  PRIMARY KEY (`id`))  
  ENGINE = InnoDB
  AUTO_INCREMENT = 3
  DEFAULT CHARACTER SET = utf8
  COLLATE = utf8_unicode_ci;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
